version: "3.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.port=9200"
      - "http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    volumes:
      - ./tmp/elastichsearch:/usr/share/elasticsearch/data
    networks:
      - esnet

  dejavu:
    image: appbaseio/dejavu:latest
    ports:
      - 127.0.0.1:1358:1358
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - esnet

  portainer:
    image: portainer/portainer
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - esnet

  # You need to build the fluentd docker image
  # to install the elasticsearch gem plugin
  fluentd:
    build: ./fluentd
    ports:
      - 127.0.0.1:24224:24224
      - 127.0.0.1:24224:24224/udp
    volumes:
      - ./config:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluentd.conf
    
  web:
    image: httpd
    ports:
      - 127.0.0.1:80:80
    logging:
      driver: fluentd
      options:
        tag: docker.httpd
    networks:
      - esnet
  
  mlflow:
    build: ./mlflow
    ports:
      - 5000:5000
    networks:
      - esnet

networks:
  esnet:
    external: true
