version: "2"
services:
  ci-workshop-demo:
    image: ci-workshop-demo:${GO_PIPELINE_LABEL}
    environment:
      - FLUENTD_HOST=${FLUENTD_HOST}
      - FLUENTD_PORT=${FLUENTD_PORT}
    ports:
      - 5005:5005
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: docker.httpd
    networks:
      - esnet

networks:
  esnet:
    external: true
