apiVersion: v1
kind: Service
metadata:
  name: ci-workshop-app-service
  labels:
    run: ci-workshop-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ci-workshop-app