# simple.gocd.yaml
pipelines:
  pipe1:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/davified/ci-workshop-app.git
    stages:
      - build: # name of stage
          elastic_profile_id: demo-app
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: echo "hello world"